### ISSUE TITLE
Videos are not waited for like images are

### ISSUE THREAD

**Issue by lencioni** [happo/happo.io#110]
Happo will wait until images are ready, but not videos. We are using the `<video>` tag and seeing spurious diffs due to this.

**Comment by lencioni** [comment]
Probably also need a robust way to ensure the video is always at the same frame.

**Comment by trotzig** [comment]
Would it make sense to just show the poster image (if there is one)?

**Comment by lencioni** [comment]
That sounds like it would work

**Comment by lencioni** [comment]
Some fixes have landed for this which have helped a lot.
