### ISSUE TITLE
Screenshots cutting off after some height

### ISSUE THREAD

**Issue by kyletov** [happo/happo.io#167]
Hey, I'm having some trouble with getting the screenshots of all the components I want to capture in a single screenshot.

Running happo works fine, but the screenshot in the report renders the first few components perfectly fine, but the later half doesn't show at all (all blank space).

I tried rendering the components individually and the screenshot captured was exactly what I was expecting. But when I put the components together under the same test, the screenshot cuts off after showing the first few components and only parts of the next component before being followed by a bunch of blank space, I assume would be the area where the remaining components would've been placed.

This is the screenshot I'm getting now that gets cut off:
<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/32151304/86495549-d6113100-bd47-11ea-86b6-6e84a64e3481.png)
</details>

These are the components that was cut off that I wanted to see (these screenshots were also taken via running happo):
<details><summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/32151304/86495933-3359b200-bd49-11ea-863c-7e721229df6b.png)
</details>

<details><summary>Screenshot 3</summary>

![image](https://user-images.githubusercontent.com/32151304/86496038-93e8ef00-bd49-11ea-9b67-cc424724db08.png)
</details>

This is my current .happo.js file that I'm using:
```
// .happo.js
const { RemoteBrowserTarget } = require('happo.io');
const craWebpackConfig = require('react-scripts/config/webpack.config');
const path = require('path');

module.exports = {
  setupScript: path.resolve(__dirname, 'src/happoSetup.js'),
  renderWrapperModule: path.resolve(__dirname, 'src/tests/happo/happoWrapper.jsx'),
  prerender: false,

  apiKey: process.env.HAPPO_API_KEY,
  apiSecret: process.env.HAPPO_API_SECRET,

  customizeWebpackConfig: config => {
    // Use the built-in webpack config provided by create-react-app
    config.module = craWebpackConfig('development').module;
    config.module.rules.push({
      resolve: {
        alias: {
          shared: path.resolve(__dirname, 'src/shared'),
          "config.js": path.resolve(__dirname, 'src/config.js'),
          css: path.resolve(__dirname, 'src/css'),
          pages: path.resolve(__dirname, 'src/pages'),
        }
      },
    });
    return config;
  },

  targets: {
    'chrome-desktop': new RemoteBrowserTarget('chrome', {
      viewport: '1024x768',
      maxHeight: 10000,
      scrollStitch: true,
    }),
  },
};
```

This is also the test file I am running on:
```
import React from 'react';
import Home from 'pages/home';

export const homePage = () => <Home />;

```

I'm not sure if I'm putting too many components into a single screenshot test or if there's a screenshot cap that I'm not aware of.

Any help on this would be great, thanks!

**Comment by trotzig** [comment]
Hi @kyletov! Tall pages like this tend to be a little tricky in general. I don't know what's going on in this specific example (haven't seen this partial cutoff where some content is rendered and some is not). It might be a rendering optimization that Chrome does (but that's just a theory). It would be interesting to see if things look the same in other browsers. Can you try adding e.g. `firefox` and `edge` to your `.happo.js` file?

**Comment by kyletov** [comment]
Hey @trotzig, I tried adding `firefox` and edge as the targets. `Firefox` was able to render all the components that I wanted to capture in a single screenshot.

But I get an error when I try running `edge`, this is the error I get as well as a couple of failed get requests.

This is the error:
`StatusCodeError: 500 - "An error occurred for browser-edge: The specified command did not complete before its timeout expired."`

These were the failed get requests:
`Failed GET https://happo.io/api/snap-requests/190415. Retrying...`

It tries 5 times before displaying the error.

**Comment by kyletov** [comment]
Is there any workaround to get `chrome` to work?

**Comment by trotzig** [comment]
Thanks for trying those other browsers, I was able to reproduce that Edge issue and have deployed a fix. For reference, the root cause was that MS Edge returns `<image>` elements for `document.body.querySelectorAll('img')`, and we ended up waiting indefinitely for `<image>` elements to load (which is an svg element, has no `load` event). Oh browser quirks... :)

It's hard to do anything about the chrome issue unfortunately. Have you checked to see if this is consistent or if it only happens now and then?

**Comment by kyletov** [comment]
Ahh I see, fun with browsers lol

And I tried running another test with a tall page on Chrome, and I get a similar result, cuts off roughly around the same point, in terms of height starting from the top of the page. And if there's more components after, it's filled up with blank space.

**Comment by trotzig** [comment]
One thing you could try here would be to remove the video banner from the top of the page (temporarily) and see if that makes any difference. I suspect Chrome is making some optimization here, and that the video could be part of the problem.

**Comment by kyletov** [comment]
Hey, I removed the video banner temporarily and tried running happo again to see if `chrome` loads the rest of the tall page. 
The screenshot generated still cuts off early and filled up the remaining space with blank space for the rest of the components that didn't render.

But the removal of the video banner component resulted in the component that got cut off before (with the video banner at the top of the page) to render more of it now, in the new screenshot.

**Comment by trotzig** [comment]
Good news -- I was able to reproduce this and found a workaround. I hope to have that deployed during the day tomorrow.

**Comment by kyletov** [comment]
That's awesome! I'll give it a test tomorrow to double check after you've deployed it, thanks!

**Comment by trotzig** [comment]
The update has now been deployed to our Chrome cluster at happo.io. Let me know what you see after this update!

**Comment by kyletov** [comment]
Hey @trotzig, I just ran on this version of happo (`happo.io@5.7.0-rc.1b`) again and it works really nicely now, loads more than before. But when I get to larger resolution sizes for Chrome, the end bit of the page is cut off.

Other resolution sizes I've tested on that works great are: `576x768`, `768x768`, `992x768`, `1200x768`.

I'm still using the `maxHeight: 10000` config for the targets. I tried increasing this config to 15000 and 20000, I still get the same result.

These are the screenshots I'm talking about:
The viewport used here is `1440x768`:
<details><summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/32151304/87453682-e095bb00-c5d0-11ea-8005-899661e958ff.png)
</details>

The viewport used below is `1920x768`:
<details><summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/32151304/87453857-2fdbeb80-c5d1-11ea-9d34-f9494435c7a8.png)
</details>

**Comment by kyletov** [comment]
I'm not sure if there was a modification in `Safari`, but I'm getting a similar kind of error for Safari. The trend of the issue I'm seems to be where the smaller the resolution(viewport), the earlier it cuts off.

I noticed this issue when I ran it on the same page when I first opened this issue, can look back and check for reference of how the full page looks like. I also ran with the same viewports as mentioned above.

Here's a sample code for the `Safari` target that I used in my Happo config file:
```
'safari-1920': new RemoteBrowserTarget('safari', {
  viewport: '1920x768',
  maxHeight: MAX_HEIGHT,
  scrollStitch: true,
}),
```

And here's a sample screenshot:
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/32151304/87458614-3cb00d80-c5d8-11ea-93f1-740c505817cf.png)
</details>

**Comment by trotzig** [comment]
Thanks for all the debugging info, this is very helpful!

> But when I get to larger resolution sizes for Chrome, the end bit of the page is cut off.

Okay, I'll look into this. There's some code that computes the total size of all the content on the page (which is important to crop away whitespace for small components) and I think that might be hurting these taller full-page examples (I think we can skip the cropping in these cases and it will be alright). The reason the computed total size is too small could be that there's dynamic content loaded which leads to a race condition. 

> I find that if I run more than 1 Happo test at the same time, the screenshots I get back are the same as the ones listed above

So it looks like the different Happo examples are affecting each other in some way. That's something we'll have to work out on our end.

**Comment by kyletov** [comment]
Hey @trotzig, wanted to follow up on this, I'm running Happo version 6.3.0, Chrome and Firefox are working as needed, even for taller full-page examples. Safari also works but only if it's running on 1 test file, if 2 test files were detected, it runs one of the test files as needed (screenshots the entire page for the viewports specified) but the other page gets cutoff early.

Not sure how Happo chooses which test file to run first, but it's been consistent with which page that experiences this. I'm assuming the 2nd test file that Happo runs is the one that usually gets this issue.

**Comment by trotzig** [comment]
Hi @kyletov! I can't remember exactly how test files are sorted, but I know it's at least consistent. I'm going to look closer at this tomorrow. In the meantime, do you have a link to a report where this is happening? You can email that to henric.trotzig@happo.io in case you don't want to share it here.

**Comment by trotzig** [comment]
Okay, I think I've found the issue here. It has to do with Safari not properly scrolling up before computing the size of the next screenshot. And I think it only applies to [Happo Examples integrations](https://docs.happo.io/docs/examples) that have [`prerender: false` set in `.happo.js`](https://docs.happo.io/docs/configuration#prerender). I'm currently deploying a fix, I'll let you know when it is available.

**Comment by trotzig** [comment]
Okay, the deploy is done. Are you able to retrigger a build to see if things have improved? 

And thanks for the report (again), your help makes happo.io better!

**Comment by kyletov** [comment]
Yup, looks good to me! I just ran a Happo test run with 2 test files detected and Safari is working as needed, thank you!

And no problem! Will let you know if anything else comes up 👍
