### ISSUE TITLE
Running happo with more than 1 test file.

### ISSUE THREAD

**Issue by kyletov** [happo/happo.io#168]
Hey, I'm having some trouble running more than 1 test file. 
For context, the two tests that I'm running together are trying to screenshot tall pages.

This is the error I get when I try to run 2 test files:
<img width="690" alt="Screen Shot 2020-07-03 at 5 53 50 PM" src="https://user-images.githubusercontent.com/32151304/86498957-622a5500-bd56-11ea-836f-6f3f506ea2cd.png">

Is there a reason for this? Not sure if this is an error on my end or vice versa.

**Comment by trotzig** [comment]
We recently ran into this issue with [happo-cypress](https://github.com/happo/happo-cypress) and I've applied the same fix here. Can you try installing `happo.io@5.7.0-rc.1b` and see if that resolves your issue? If so, I'll clean it up and release properly,.

**Comment by kyletov** [comment]
I installed `happo.io@5.7.0-rc.1b` and tried again. I don't get the error now and happo ran got the screenshots successfully. 
Thanks @trotzig!

**Comment by trotzig** [comment]
Okay, great! I’ll include the fix in the next release. In the meantime you can use the rc version.
