### ISSUE TITLE
Error: Error: The NODE_ENV environment variable is required but was not specified.

### ISSUE THREAD

**Issue by kyletov** [happo/happo.io#170]
Hey, I'm getting this error and I'm not sure why I need to specify NODE_ENV. Can I get some clarifications on why it's needed to be specified? Thanks!

This is the file where the error occurred: `node_modules/happo.io/build/loadUserConfig.js:47:11`

**Comment by trotzig** [comment]
Are you using create-react-app? I remember this being a quirk with loading cra's webpack config, as in this demo example: https://github.com/happo/happo-cra-typescript#2-configure-happojs

In this project, I have the `happo` script set up to automatically inject NODE_ENV. Would that work in your case? 
https://github.com/happo/happo-cra-typescript/blob/7abd361753b0fd00fca342ff063e20840e6a5b9c/package.json#L20

**Comment by kyletov** [comment]
Ahh it works, thanks!
