### ISSUE TITLE
Environment variables in CircleCI run

### ISSUE THREAD

**Issue by kyletov** [happo/happo.io#187]
Is it possible to set custom environment variables in CircleCI runs? I'm trying to define an environment variable `IS_HAPPO_TEST=true` when a Happo test is running.

Is it possible to tell at runtime (when the page is being screenshotted) whether the current request is from Happo within our React App?

**Comment by trotzig** [comment]
Hi @kyletov! What [type of integration](https://docs.happo.io/docs/getting-started#choose-an-integration) are you using? Environment variables are handled differently depending on the integration. For Happo examples, you'd have to inject the environment variables into the webpack bundled created by Happo, via [customizeWebpackConfig](https://docs.happo.io/docs/configuration#customizewebpackconfig). It looks like you can do this via the [EnvironmentPlugin for webpack](https://webpack.js.org/plugins/environment-plugin/).

**Comment by kyletov** [comment]
Hey @trotzig, I'm currently using the Happo Examples Integration. I'll try the suggestions you mentioned and update if anything comes up, thanks!
