### ISSUE TITLE
Failures running Happo - File Already Exists

### ISSUE THREAD

**Issue by kyletov** [happo/happo.io#193]
Hey @trotzig, I'm currently running Happo Examples Integration and have been getting this error a couple times when Happo is ran via `happo-ci-circleci`:

`StatusCodeError: 500 - "An error occurred for browser-safari: EEXIST: file already exists`

Takes 1 or more reruns to get a successful Happo run without erroring out, any ideas for why this is occurring?

**Comment by trotzig** [comment]
Hi @kyletov! This was an issue I found on the weekend (was running an old version of Node on one worker). Are you seeing this right now? There might be a worker I missed.

**Comment by kyletov** [comment]
Hey @trotzig, I haven't made a commit to check, but I got this error around 2 weeks ago. Since you found this issue recently, I'll let you know if I see the error again, thanks!

**Comment by trotzig** [comment]
Okay, good to know! I made another check to make sure that I hadn't left any of the workers out. Sorry about the instability!

**Comment by kyletov** [comment]
No worries, thanks for the fixes/updates!
