### ISSUE TITLE
Spurious diffs with iOS-safari

### ISSUE THREAD

**Issue by ahobson** [happo/happo.io#196]
This happens to us a *lot*:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/21983/108527235-0f2eef00-72a0-11eb-9362-7449146646ac.png">

In particular, it seems like iOS-safari frequently has diffs related to icon assets not loading consistently.

Any advice?

**Comment by trotzig** [comment]
Hi @ahobson! Sorry about this -- these shouldn't be showing up like this. Do you have a link to a report I can look at? You can send it to support@happo.io, I'll investigate to see what's up.

**Comment by trotzig** [comment]
Okay, the theory right now is that we aren't waiting for background images on pseudo elements to finish before we take the screenshot. I'll update this thread once we have a fix. Appreciate the report @ahobson!

**Comment by trotzig** [comment]
The theory was correct. A fix has been deployed to Happo's workers.

**Comment by ahobson** [comment]
Thank you. We had a number of PRs from dependabot this morning and we didn't see this issue at all
