### ISSUE TITLE
Images created by `next/image` are not rendered in screenshots

### ISSUE THREAD

**Issue by matthieu-foucault** [happo/happo.io#223]
Not quite sure what is causing it, if it's a bug or something that just needs to be documented.

Our Next.js application has a logo rendered using the [Next.js Image component](https://nextjs.org/docs/basic-features/image-optimization). Happo jobs are triggered by `happo-cypress`, and the image is present in the assets collected by Happo.

The screenshots, however, do not display the image, using the Chrome, Firefox, Edge, or Safari browser, only the alt text

Changing the Image to use an HTML `img` element fixes the issue, as shown in this [happo report](https://happo.io/a/336/p/1010/compare/ed0c774a7ec76cf03c67f2230b0c7947bedc38a0/dev-6818a47c)

**Comment by trotzig** [comment]
Hi Matthieu! Thanks for the report. This definitely seems like a bug -- let me investigate this tomorrow. We're using Next.js internally for Happo.io as well, so hopefully this shouldn't be hard to reproduce.

**Comment by trotzig** [comment]
I totally forgot about this 🤦‍♂️

Having a look now.

**Comment by matthieu-foucault** [comment]
Those workarounds do not fix the issue, nor they are applicable in my case as my next image has the `priority` prop, which means it will be pre-loaded.
In my bug the alt text is being rendered, not the blank placeholder.

I made progress though, and found that using **an SVG image is what causes the issue** switching it to a PNG file fixes it.

**Comment by trotzig** [comment]
Oh, okay -- that's good info! I'll try reproducing it with an svg this time.

**Comment by matthieu-foucault** [comment]
Before I added the `priority` prop to my image I did see spurious diffs where sometimes the blank placeholder was rendered, so there's probably a need for that workaround for images that are not preloaded.

In my case the `priority` prop is needed as the image in question is a logo in the page's header, and not having it makes the page do an initial render with the blank placeholder before the image load, which is not great UX.

**Comment by trotzig** [comment]
I played around with the `priority` prop and found it to help as well. 

The svg test showed me something interesting however -- all the `next/image` images are saved into a file called `.next/image` (no extension). The first stored image wins, so my svg image is showing up as a previous png. I should be able to fix this in the happo-cypress package.

**Comment by trotzig** [comment]
Alright, I think I have this taken care of now. If you update to [happo-cypress@3.0.1](https://github.com/happo/happo-cypress/releases/tag/v3.0.1), the image should be included in the Happo screenshot. Let me know if that doesn't work!

**Comment by matthieu-foucault** [comment]
That did fix the issue, thanks!
