### ISSUE TITLE
Failure due to maxHeight not being applied

### ISSUE THREAD

**Issue by cassiourugit** [happo/happo.io#251]
This problem started to occur this month with me

My .happo.js looks like this

```
const { RemoteBrowserTarget } = require('happo.io');
const happoPluginStorybook = require('happo-plugin-storybook');

module.exports = {
  apiKey: process.env.HAPPO_API_KEY,
  apiSecret: process.env.HAPPO_API_SECRET,

  targets: {
    chrome: new RemoteBrowserTarget('chrome', {
      viewport: '1024x768',
      maxHeight: 10000,
    }),
    firefox: new RemoteBrowserTarget('firefox', {
      viewport: '1024x768',
      maxHeight: 10000,
    }),
    edge: new RemoteBrowserTarget('edge', {
      viewport: '1024x768',
      maxHeight: 10000,
    }),
    safari: new RemoteBrowserTarget('safari', {
      viewport: '1024x768',
      maxHeight: 10000,
    }),
  },

  project: process.env.HAPPO_PROJECT,

  plugins: [
    happoPluginStorybook({
      configDir: './.storybook-happo',
    }),
  ],

  type: 'react',
};
```

And i have about 250 snapshots 
Some of the snapshots have a lot of height, and this was never an issue until recently.
My tests now started to fail because it is loading with the height 768, instead of rendering the full height of the page.

Like this
![Captura de Tela 2023-03-09 às 14 11 02](https://user-images.githubusercontent.com/31551486/224105694-bc0c3494-3f6d-49a5-a0de-6efd9c57b279.png)

This only occur when i run my full tests with over 250 snapshots.
If i run with only this color page of my picture, it load the full height no problems

Did anyone know what is happening?

**Comment by trotzig** [comment]
Hi @cassiourugit! This is a long-shot, but could it be that one of your components locks the height of the <body> element? That could explain why you're only seeing it when rendered together with other snapshots. 

If you have a link to a report where this occurs, send it to support@happo.io and I can look at it.

**Comment by cassiourugit** [comment]
Hi @trotzig!

That makes sense, i will take a look at this.

Heres the a link to a failed report
https://happo.io/a/905/p/1312/compare/release170/release180d

**Comment by trotzig** [comment]
Thanks! 

It looks like something (not sure which component) is setting `overflow: hidden;` on the `<body>` element. See if you can pinpoint what component/story is doing that, and see if you can clean up that bit of styling when the component is unmounted. 

If you're interested in how I debugged this, I went through these steps: 
- On the report page, click the overflow menu next to a diff (any, really)
- Select "View source for after image". This will lead to a zip file being downloaded. 
- Unpack the zip file and run `npx http-server /path/to/unzipped/folder`
- Go to the URL given to us by http-server and add `/iframe.html` to the url, i.e. http://127.0.0.1:8080/iframe.html
- Run this javascript snippet in the browser js console: 
```js
var renderIter = function () {
  window.happo.nextExample().then(function (a) {
    if (!a) {
      return;
    }
    console.log(a);
    renderIter();
  });
};
renderIter();
```
- When all the components have been rendered, inspect the DOM

This type of debugging is also described at https://docs.happo.io/docs/storybook#debugging

**Comment by cassiourugit** [comment]
Wow, perfect!

I think it was not the overflow, since it's there from the start.
But, using your method of debugging, i was able to identify that my BottomSheet web component was the source of trouble.

Once it loaded, every other page already loaded lost the scroll ability.

I will take a look on whats going on with my component.

Thanks so much @trotzig 
You are awesome!

**Comment by trotzig** [comment]
Excellent! Glad I could be of (some) help! 🙂
