### ISSUE TITLE
Request to apply a lock if the test is going to exceed the number of available snapshots

### ISSUE THREAD

**Issue by cassiourugit** [happo/happo.io#256]
It would be great if there was an option to prevent a test to happen if the number of snapshots in the current run exceeds the available snapshots.

If this is not officially implemented, do you guys know any way where i can do that at my end? The finance department at my job is demanding this a lot.

**Comment by trotzig** [comment]
Hi @cassiourugit! There's no way to do this right now unfortunately. I wonder if an API endpoint where you can get the current quota status would be enough? Something like 

```
GET https://happo.io/api/usage

JSON response: 
{ 
  "total": 234312,
  "start": "2023-04-22",
  "end": "2023-05-22",
  "quota": 500000
}
```

Let me know what you think!

**Comment by cassiourugit** [comment]
That would be perfect!
With that i can do the validations on my end before calling the test

**Comment by trotzig** [comment]
You can try the new API endpoint now: 
https://happo.io/docs/api#billingCurrentUsage

I still have some things to take care of (looks like dates are either missing or in the wrong format) but the total and quota properties are correct.

**Comment by cassiourugit** [comment]
Thanks so much! That works like a charm
