### ISSUE TITLE
Incorrect SHA in the final comparison report

### ISSUE THREAD

**Issue by dmaklygin** [happo/happo.io#275]
`PREVIOUS_SHA` replaced with master branch SHA after report completion.

We are experiencing an issue with `Happo` where the `PREVIOUS_SHA` is being replaced with the SHA from the `master` branch after the report is completed. Here are the details of our setup and the issue:

Setup:

	1.	We use `Happo` within `Storybook`.
	2.	We call `happo-ci-github-actions` with predefined environment variables:
	•	HAPPO_PROJECT: Picasso/Storybook
	•	HAPPO_API_KEY: ${{ env.HAPPO_API_KEY }}
	•	HAPPO_API_SECRET: ${{ env.HAPPO_API_SECRET }}
	•	PREVIOUS_SHA: ${{ github.event.pull_request.base.sha }} ("1252164f6ca4df5bf6f095079707afddc1b7a9f4")

Issue:

	1.	After starting the job, Happo provides a **proper** link to the report page: https://happo.io/a/675/jobs/1187395
	2.	Once the report is ready, the link changes to: https://happo.io/a/675/p/1189/compare/a9768dd9cd4a118a4ae61857124eed0fa84e0090/7ddc840fdd5f3825f44b666d67b8e3ed131c2ad8
	3.	The SHA a9768dd9cd4a118a4ae61857124eed0fa84e0090 corresponds to the master branch, but it should be 1252164f6ca4df5bf6f095079707afddc1b7a9f4.

Logs:
Here are some logs from the [job](https://github.com/toptal/picasso/actions/runs/9319744678/job/25655348679?pr=4342) for reference:
```
Using the following ENV variables:
PREVIOUS_SHA: 1252164f6ca4df5bf6f095079707afddc1b7a9f4
CURRENT_SHA: 7ddc840fdd5f3825f44b666d67b8e3ed131c2ad8
CHANGE_URL: https://github.com/toptal/picasso/pull/4342
INSTALL_CMD: 
HAPPO_IS_ASYNC: true
HAPPO_SKIP_START_JOB: 
HAPPO_GIT_COMMAND: git
HAPPO_COMMAND: node_modules/happo.io/build/cli.js
HAPPO_FALLBACK_SHAS_COUNT: 50
```

Job link: [GitHub Actions job log](https://github.com/toptal/picasso/actions/runs/9319744678/job/25655348679?pr=4342)

It appears that PREVIOUS_SHA is correctly set initially, but it is replaced by the master branch SHA in the final report. This causes the visual comparison to be inaccurate as it does not reflect the intended base commit.

We appreciate your assistance in resolving this issue.

Link to the PR to test: https://github.com/toptal/picasso/pull/4342

**Comment by trotzig** [comment]
Hi @dmaklygin, sorry for the delay here. 🙏

The most likely thing that's happening here is that the sha for `PREVIOUS_SHA` doesn't have a Happo report generated for it. Happo will then use a fallback SHA, starting from PREVIOUS_SHA and moving backwards. It happens [in the happo-ci script, here](https://github.com/happo/happo.io/blob/df19115fc8c85be2a39c565a997a0519b45ad836/bin/happo-ci#L28). 

Can you check to make sure that Happo reports are generated on the master branch and that the jobs are successful? If not, that's where we should start.

**Comment by dmaklygin** [comment]
Hi, @trotzig !
Thank you for your response. Seems, the issue is fixed now. Your suggestion helped to have proper reports.
I suppose we can close the issue now
