### ISSUE TITLE
Transitive dependency missing

### ISSUE THREAD

**Issue by ahuth** [happo/happo.io#73]
After https://www.npmjs.com/advisories/830, it looks like all but the latest version of Ecstatic was removed from NPM (see https://github.com/jfhbrook/node-ecstatic/issues/255). This is an issue because it's a dependency of http server (https://github.com/indexzero/http-server/issues/521), which is a dependency of happo.io.

Because of this, I'm unable to install the package. The only solution may be to ensure that http-server is updated here, once they update.

**Comment by trotzig** [comment]
Thanks for making me aware of this problem. The http-server dependency isn't vital for main happo execution (it is only used for `happo debug`), I think I can ditch that dependency temporarily.

**Comment by trotzig** [comment]
The fix was released in `v3.14.0` - https://www.npmjs.com/package/happo.io/v/3.14.0

**Comment by ahuth** [comment]
Thanks!

**Comment by thornjad** [comment]
jfhbrook/node-ecstatic#256 will fix http-server
