### ISSUE TITLE
wrong PREVIOUS_SHA using happo-ci-circleci

### ISSUE THREAD

**Issue by ggazzo** [happo/happo.io#79]
we are testing happo here at [Rocket.chat](https://github.com/RocketChat) and we faced that script:
```shell
PREVIOUS_SHA=$(git merge-base origin/master "${CIRCLE_SHA1}")
```

my question:
should `origin/master` be `origin/"BASE"`?

**Comment by trotzig** [comment]
You are right, it shouldn't assume `master`. I'll address this right away, it will probably involve optionally setting a `BASE_BRANCH` environment variable to override the default.

**Comment by trotzig** [comment]
Release 3.18.0 was released with a way to set the base branch using the `BASE_BRANCH` env variable: 

```bash
BASE_BRANCH=origin/dev npm run happo-ci
```

Please note that you need to include the full branch name, e.g. `origin/dev` (and not `dev`).
