### ISSUE TITLE
Blank screenshots for components that are mostly rendered in portals

### ISSUE THREAD

**Issue by lencioni** [happo/happo.io#95]
We have a component that renders everything inside a portal (created by using react-dom's `createPortal`). The screenshots for this component are always blank. Looking at the source in the happo report and most of the DOM nodes for these examples are missing.

I dug through the code, and I believe that our problem lies in this code: https://github.com/happo/happo.io/blob/2ff1257f757d1d5f8ba0f5bdff4a3c44d780fdeb/src/browser/processor.js#L12-L32

It looks like happo has some logic to account for examples that are rendered entirely inside a portal (checks to see if the root element is completely empty), however in our case there is some content that is rendered in the root element (a div or two, but with no styling) and most of the interesting bits are inside the portal.

**Comment by lencioni** [comment]
I think the main problem here is that this code assumes there is a single root, but with portals there can be multiple roots.

**Comment by trotzig** [comment]
I've made a change that will detect these scenarios and use `document.body` as the root. I published a version under the `next` tag on in case you want to try this out right away. 

```bash
npm install --save-dev happo.io@3.22.0-rc.1
```
or
```bash
npm install --save-dev happo.io@next
```
